AMREX_HOME ?= /Users/ashwathsv/amrex
PRECISION  = DOUBLE
# TINY_PROFILE = TRUE
# PROFILE      = FALSE
# AMREX_ENABLE_TINY_PROFILE = ON
# AMREX_ENABLE_BASE_PROFILE = OFF

DEBUG      = TRUE
# DEBUG      = FALSE

DIM        = 2
#DIM       = 3

COMP	   = gnu
CXXSTD     = c++11

USE_MPI    = TRUE
USE_OMP    = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.Adv
